config/routes.rb
# Plugin's routes
resources :projects do
  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include Redmine::SafeAttributes

  validates :name, :presence => true

  attr_protected :id

  safe_attributes 'name', 'project_id', 'custom_fields', 'custom_field_values'
  acts_as_customizable
  acts_as_attachable delete_permission: :delete_contacts, view_permission: :view_contacts
  belongs_to :project

  acts_as_event :datetime => :updated_at,
                :description => nil,
                :title => Proc.new {|o| "#{l(:label_contact_name)} #{o.name}"},
                :url => Proc.new {|o| {:controller => 'contacts', :action => 'show', :id => o, :project_id => o.project_id}},
                :author => nil

  acts_as_activity_provider :type => 'contacts',
                            :permission => nil,
                            :timestamp => :updated_at,
                            :author_key => nil,
                            :scope => joins(:project)

  acts_as_searchable :columns => "#{table_name}.name", :date_column => 'created_at'

  scope :visible, lambda {|*args|
    joins(:project).
        where(Project.allowed_to_condition(args.shift || User.current, :view_contacts, *args))}

  # Returns true if the contact can be edited by user, otherwise false
  def editable_by?(usr)
    usr.allowed_to?(:edit_contact, project) || usr.allowed_to?(:delete_contacts, project)
  end
end

app/models/contact_custom_field.rb
class ContactCustomField < CustomField

  def type_name
    :label_contact_plural
  end
end

app/models/contact_query.rb
class ContactQuery < Query
  self.queried_class = Contact

  self.available_columns = [
      QueryColumn.new(:name, :sortable => "#{Contact.table_name}.name", :groupable => true, :default_order => 'desc'),
      QueryColumn.new(:created_at, :sortable => "#{Contact.table_name}.created_at", :default_order => 'desc'),
      QueryColumn.new(:updated_at, :sortable => "#{Contact.table_name}.updated_at", :default_order => 'desc')
  ]

  def initialize(attributes=nil, *args)
    super attributes
    self.filters ||= {}
  end

  def initialize_available_filters
    add_available_filter "name", :type => :text
    add_available_filter "project_id", :type => :integer
    add_available_filter "created_at", :type => :float
    add_available_filter "updated_at", :type => :float
    add_custom_fields_filters(ContactCustomField)
  end

  def available_columns
    return @available_columns if @available_columns
    @available_columns = self.class.available_columns.dup
    @available_columns += ContactCustomField.visible.
        map {|cf| QueryCustomFieldColumn.new(cf) }
    @available_columns
  end

  def default_columns_names
    @default_columns_names ||= [:project, :name, :created_at, :updated_at]
  end

  def results_scope(options={})
    order_option = [group_by_sort_order, options[:order]].flatten.reject(&:blank?)

    Contact.visible.where(statement).order(order_option)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  helper :custom_fields
  helper :attachments
  include AttachmentsHelper
  helper :queries
  include QueriesHelper
  helper :sort
  include SortHelper

  before_filter :find_contact, :only => [:edit, :update, :destroy, :show]
  before_filter :find_optional_project

  def index

    @query = ContactQuery.build_from_params(params, :project => @project, :name => '_')

    sort_init(@query.sort_criteria.empty? ? [['name', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)
    scope = contact_scope(:order => sort_clause).
        includes(:project)

        @entry_count = scope.count
        @entry_pages = Paginator.new @entry_count, per_page_option, params['page']
        @entries = scope.offset(@entry_pages.offset).limit(@entry_pages.per_page).to_a

        render :layout => !request.xhr?
  end

  def new
    @contact = Contact.new
    @contact.safe_attributes = params[:contact]
  end

  def create
    @contact = Contact.new
    @contact.safe_attributes = params[:contact]
    @contact.save_attachments(params[:attachments])
    if @contact.save
      render_attachment_warning_if_needed(@contact)
      flash[:notice] = l(:notice_successful_create)
      redirect_to project_contacts_path(@project)
    else
      flash[:alert] = l(:notice_params_needed)
      render :action => 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @contact.safe_attributes = params[:contact]
    @contact.save_attachments(params[:attachments])
    if @contact.update_attributes(params[:contact])
      render_attachment_warning_if_needed(@contact)
      flash[:notice] = l(:notice_successful_update)
      redirect_to project_contacts_path(@project)
    else
      render :action => 'edit', project_id: @contact.project_id
    end
  end

  def destroy
    @contact.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to project_contacts_path(@project)
  end

  private

  def find_contact
    @contact = Contact.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def contact_scope(options={})
    scope = @query.results_scope(options)
    scope
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.erb
<%= form_for ([@project, @contact]) do |f| %>
    <%= f.label :name%>*<br>
    <%= f.text_field :name %><br>
    <%= f.hidden_field :project_id, :value => @project.id %><br>
    <% @contact.custom_field_values.each do |value| %>
        <p><%= custom_field_tag_with_label :contact, value %></p>
    <% end %>
    <div class="box">
      <p>
        <label><%=l(:label_attachment_plural)%></label>
        <%= render :partial => 'attachments/form' %>
      </p>
    </div>
    <%= f.submit %>
<% end %>

app/views/contacts/_list.html.erb
<%= form_tag({}) do -%>
    <%= hidden_field_tag 'back_url', url_for(params) %>
    <div class="autoscroll">
      <table class="list time-entries">
        <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <% @query.inline_columns.each do |column| %>
              <%= column_header(column) %>
          <% end %>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% entries.each do |entry| -%>
            <tr class="time-entry <%= cycle("odd", "even") %> hascontextmenu">
              <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", entry.id, false, :id => nil) %></td>
               <%= raw @query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, entry)}</td>"}.join %>
              <td class="buttons">
                <% if entry.editable_by?(User.current) -%>
                    <%= link_to l(:button_edit), edit_project_contact_path(@project, entry),
                                :title => l(:button_edit),
                                :class => 'icon-only icon-edit' %>
                    <%= link_to l(:button_delete), project_contact_path(@project, entry),
                                :data => {:confirm => l(:text_are_you_sure)},
                                :method => :delete,
                                :title => l(:button_delete),
                                :class => 'icon-only icon-del' %>
                <% end -%>
              </td>
            </tr>
        <% end -%>
        </tbody>
      </table>
    </div>
<% end -%>

app/views/contacts/edit.html.erb
<%= render 'form' %>

app/views/contacts/index.html.erb
<% unless @entries.empty? %>
<%= render :partial => 'list', :locals => { :entries => @entries }%>
<span class="pagination"><%= pagination_links_full @entry_pages, @entry_count %></span>
<%end%>
<p>
<% if User.current.allowed_to?(:create_contact,@project) %>
    <%= link_to 'new contact', new_project_contact_path(@project) %><br>
<%end%>
</p>

app/views/contacts/new.html.erb
<%= render 'form'%>

app/views/contacts/show.html.erb
<%= link_to_attachments @contact,
  :thumbnails => false,
  :author => true%>

<%= link_to 'back', project_contacts_path%>